apiVersion: apps/v1
kind: Deployment
metadata:
  name: kevacoind
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kevacoind
  template:
    metadata:
      labels:
        app: kevacoind
    spec:
      containers:
        - name: kevacoind
          imagePullPolicy: Always
          image: dougflynn/kevacoind:latest
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: kevacoind-cluster-ip
spec:
  # type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: kevacoind
